package com.example.animalgame;

import android.content.Context;
import android.media.MediaPlayer;
import android.util.Log;

public class Sound extends MainActivity {

//    public static final int sounds = {
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//            R.raw.bear, R.raw.cat, R.raw.chicken, R.raw.chick, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.duck, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.turkey, R.raw.wolf,
//
//
//    };
    public static final int[] sounds = new int[]{
        R.raw.bear, R.raw.bee, R.raw.bird, R.raw.cat, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.snake, R.raw.turkey, R.raw.wolf,
        R.raw.bear, R.raw.bee, R.raw.bird, R.raw.cat, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.snake, R.raw.turkey, R.raw.wolf,
        R.raw.bear, R.raw.bee, R.raw.bird, R.raw.cat, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.snake, R.raw.turkey, R.raw.wolf,
        R.raw.bear, R.raw.bee, R.raw.bird, R.raw.cat, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.snake, R.raw.turkey, R.raw.wolf,
        R.raw.bear, R.raw.bee, R.raw.bird, R.raw.cat, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.snake, R.raw.turkey, R.raw.wolf,
        R.raw.bear, R.raw.bee, R.raw.bird, R.raw.cat, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.snake, R.raw.turkey, R.raw.wolf,
        R.raw.bear, R.raw.bee, R.raw.bird, R.raw.cat, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.snake, R.raw.turkey, R.raw.wolf,
        R.raw.bear, R.raw.bee, R.raw.bird, R.raw.cat, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.snake, R.raw.turkey, R.raw.wolf,
        R.raw.bear, R.raw.bee, R.raw.bird, R.raw.cat, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.snake, R.raw.turkey, R.raw.wolf,
        R.raw.bear, R.raw.bee, R.raw.bird, R.raw.cat, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.snake, R.raw.turkey, R.raw.wolf,
        R.raw.bear, R.raw.bee, R.raw.bird, R.raw.cat, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.snake, R.raw.turkey, R.raw.wolf,
        R.raw.bear, R.raw.bee, R.raw.bird, R.raw.cat, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.snake, R.raw.turkey, R.raw.wolf,
        R.raw.bear, R.raw.bee, R.raw.bird, R.raw.cat, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.snake, R.raw.turkey, R.raw.wolf,
        R.raw.bear, R.raw.bee, R.raw.bird, R.raw.cat, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.snake, R.raw.turkey, R.raw.wolf,
        R.raw.bear, R.raw.bee, R.raw.bird, R.raw.cat, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.snake, R.raw.turkey, R.raw.wolf,
        R.raw.bear, R.raw.bee, R.raw.bird, R.raw.cat, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.snake, R.raw.turkey, R.raw.wolf,
        R.raw.bear, R.raw.bee, R.raw.bird, R.raw.cat, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.snake, R.raw.turkey, R.raw.wolf,
        R.raw.bear, R.raw.bee, R.raw.bird, R.raw.cat, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.snake, R.raw.turkey, R.raw.wolf,
        R.raw.bear, R.raw.bee, R.raw.bird, R.raw.cat, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.snake, R.raw.turkey, R.raw.wolf,
        R.raw.bear, R.raw.bee, R.raw.bird, R.raw.cat, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.snake, R.raw.turkey, R.raw.wolf,
        R.raw.bear, R.raw.bee, R.raw.bird, R.raw.cat, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.snake, R.raw.turkey, R.raw.wolf,
        R.raw.bear, R.raw.bee, R.raw.bird, R.raw.cat, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.snake, R.raw.turkey, R.raw.wolf,
        R.raw.bear, R.raw.bee, R.raw.bird, R.raw.cat, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.snake, R.raw.turkey, R.raw.wolf,
        R.raw.bear, R.raw.bee, R.raw.bird, R.raw.cat, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.snake, R.raw.turkey, R.raw.wolf,
        R.raw.bear, R.raw.bee, R.raw.bird, R.raw.cat, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.snake, R.raw.turkey, R.raw.wolf,
        R.raw.bear, R.raw.bee, R.raw.bird, R.raw.cat, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.snake, R.raw.turkey, R.raw.wolf,
        R.raw.bear, R.raw.bee, R.raw.bird, R.raw.cat, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.snake, R.raw.turkey, R.raw.wolf,
        R.raw.bear, R.raw.bee, R.raw.bird, R.raw.cat, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.snake, R.raw.turkey, R.raw.wolf,
        R.raw.bear, R.raw.bee, R.raw.bird, R.raw.cat, R.raw.cock, R.raw.cow, R.raw.dog, R.raw.donkey, R.raw.dove, R.raw.elephant, R.raw.frog, R.raw.goat, R.raw.goose, R.raw.horse, R.raw.lion, R.raw.monkey, R.raw.sheep, R.raw.snake, R.raw.turkey, R.raw.wolf

};


    public static void playSound(Context context, int soundID) {
        try {
            MediaPlayer mediaPlayer = MediaPlayer.create(context, soundID);
            mediaPlayer.start();
        } catch (Exception e) {
            Log.d("FFF", e.toString());
        }
    }


}
